# Generated by Django 5.2 on 2025-07-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
