# Generated by Django 5.2.4 on 2025-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0002_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='role',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Mentor', 'Mentor'), ('Trainer', 'Trainer'), ('HR', 'HR')], default='Intern', max_length=50),
        ),
    ]
