# Generated by Django 5.1.2 on 2025-07-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0003_leaverequest_name_leaverequest_role'),
        ('growtern', '0005_remove_intern_mentor'),
    ]

    operations = [
    ]
