# Generated by Django 5.2.4 on 2025-07-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0003_leaverequest_name_leaverequest_role'),
        ('growtern', '0005_remove_intern_mentor'),
    ]

    operations = [
    ]
