# Generated by Django 5.2.4 on 2025-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0006_merge_20250722_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document',
            field=models.FileField(upload_to='uploaded_documents/'),
        ),
    ]
