# Generated by Django 5.1.2 on 2025-07-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0006_merge_20250722_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='growtern.mentor'),
        ),
    ]
