# Generated by Django 5.1.6 on 2025-07-23 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0007_alter_uploadeddocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='college',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='intern',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorassignment',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mentorassignment',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='growtern.intern'),
        ),
        migrations.AlterField(
            model_name='mentorassignment',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'MENTOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
