# Generated by Django 5.1.2 on 2025-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], max_length=20)),
                ('mentor', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
