# Generated by Django 5.1.2 on 2025-07-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0004_remove_mentor_email_alter_intern_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='mentor',
        ),
    ]
