# Generated by Django 5.1.2 on 2025-07-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0007_intern_mentor'),
        ('growtern', '0008_alter_intern_college_alter_intern_status_and_more'),
    ]

    operations = [
    ]
