# Generated by Django 3.2.20 on 2025-07-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growtern', '0009_merge_20250725_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='mentor',
        ),
    ]
